version: '3.3'

services:

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    image: my_app
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"

  seed_mongo:
    build:
      context: ./seed
      dockerfile: Dockerfile
    depends_on:
      - mongodb
